In [1]:
import os
import pandas as pd

In [2]:
dir = r'C:\Users\misti.wudtke\OneDrive - USDA\PROJECTS\FY25_Q2_EmployeeLocations_50mi_MatthGoldsboro\Input Files'

file_list = [os.path.join(dir, f) for f in os.listdir(dir) if f.split('.')[-1] in ['xlsx', 'csv']]

In [3]:
dfs = []

agencies = ['NRCS', 'FSA', 'RMA']

convert_cols = ['Site ID', 'Office ID', 'Total Staff', 'Total Seats', 'Available Seats']

for fl in file_list:

    if fl.endswith('.xlsx'):
        with pd.ExcelFile(fl) as fobj:
            for sheet in fobj.sheet_names:
                df = pd.read_excel(fobj, sheet)

    elif fl.endswith('.csv'):
        df = pd.read_csv(fl)

    for c in convert_cols:
        if c in df.columns:
            df[c] = df[c].astype(float)

    for a in agencies:
        if a in fl:
            df['Agency'] = a

    dfs.append(df)

In [4]:
smasht = pd.concat(dfs)

smasht.shape

(4650, 22)

In [5]:
smasht.to_excel('First_Output.xlsx', index=False)

smasht.head()

,Site ID,Site Name,Office ID,Office Name,State Name,Office Name Alt,Address,City,State Abbr,Zip,...,Agency,County,Total Staff,Office Status,Point of Contact (POC),POC Email,Comments,Created By,Modified,Modified By
0,5179.0,FSA & RURAL DEVELOPMENT STATE OFFICE-MONTGOMERY,100441.0,ALABAMA STATE FARM SERVICE AGENCY,ALABAMA,ALABAMA STATE OFFICE,4121 CARMICHAEL RD,MONTGOMERY,AL,36106-2872,...,FSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2561.0,ALASKA STATE OFFICES,80040.0,ALASKA STATE FARM SERVICE AGENCY,ALASKA,ALASKA STATE OFFICE,"800 E. PALMER-WASILLA HWY., SUITE 216",PALMER,AK,99645,...,FSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8156.0,PHOENIX STATE OFFICE,104741.0,ARIZONA STATE FARM SERVICE AGENCY,ARIZONA,ARIZONA STATE OFFICE,"230 N. 1ST AVENUE, SUITE 506",PHOENIX,AZ,85003,...,FSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5427.0,ARKANSAS USDA STATE OFFICES,101205.0,ARKANSAS STATE FARM SERVICE AGENCY,ARKANSAS,ARKANSAS STATE OFFICE,"700 W CAPITOL, RM. 3416",LITTLE ROCK,AR,72201,...,FSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5525.0,CALIFORNIA STATE OFFICES,101395.0,CALIFORNIA STATE FARM SERVICE AGENCY,CALIFORNIA,CALIFORNIA STATE OFFICE,430 G ST #4161,DAVIS,CA,95616-4161,...,FSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
cols = ['Site ID',
        'Site Name',
        'Office ID',
        'Office Name',
        'Agency',
        'State Name',
        'Address',
        'City',
        'State Abbr',
        'Zip',
        'Total Staff',
        'Total Seats',
        'Available Seats']

distil1 = smasht[cols]

distil1.head()

,Site ID,Site Name,Office ID,Office Name,Agency,State Name,Address,City,State Abbr,Zip,Total Staff,Total Seats,Available Seats
0,5179.0,FSA & RURAL DEVELOPMENT STATE OFFICE-MONTGOMERY,100441.0,ALABAMA STATE FARM SERVICE AGENCY,FSA,ALABAMA,4121 CARMICHAEL RD,MONTGOMERY,AL,36106-2872,NaN,24.0,3.0
1,2561.0,ALASKA STATE OFFICES,80040.0,ALASKA STATE FARM SERVICE AGENCY,FSA,ALASKA,"800 E. PALMER-WASILLA HWY., SUITE 216",PALMER,AK,99645,NaN,6.0,0.0
2,8156.0,PHOENIX STATE OFFICE,104741.0,ARIZONA STATE FARM SERVICE AGENCY,FSA,ARIZONA,"230 N. 1ST AVENUE, SUITE 506",PHOENIX,AZ,85003,NaN,17.0,2.0
3,5427.0,ARKANSAS USDA STATE OFFICES,101205.0,ARKANSAS STATE FARM SERVICE AGENCY,FSA,ARKANSAS,"700 W CAPITOL, RM. 3416",LITTLE ROCK,AR,72201,NaN,36.0,5.0
4,5525.0,CALIFORNIA STATE OFFICES,101395.0,CALIFORNIA STATE FARM SERVICE AGENCY,FSA,CALIFORNIA,430 G ST #4161,DAVIS,CA,95616-4161,NaN,19.0,0.0

In [7]:
# Here is a handy block for removing all leading/trailing whitespace
# in all string columns in the df:
for col in distil1.columns:
    if distil1[col].dtype == 'object':
        distil1[col] = distil1[col].str.strip()

C:\Users\misti.wudtke\AppData\Local\Temp\ipykernel_20984\2988165192.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  distil1[col] = distil1[col].str.strip()

In [8]:
distil1.to_excel('Second_Output_Distilled.xlsx', index=False)

distil1.shape

(4650, 13)

In [9]:
dups = distil1[distil1['Site ID'].duplicated()]

dups.to_excel('dups.xlsx', index=False)

dups.shape

(51, 13)

In [10]:
all_dups = distil1[distil1['Site ID'].isin(dups['Site ID'])]

all_dups.to_excel('all_dups.xlsx', index=False)

all_dups.shape

(95, 13)

In [ ]:
oip = r"C:\Users\misti.wudtke\OneDrive - USDA\PROJECTS\FY25_Q2_EmployeeLocations_50mi_MatthGoldsboro\Script and Outputs\COMPLETE OIP Workload Analysis 20250121 (1).xlsx"

# There's only 1 sheet
oip_df = pd.read_excel(oip)

In [ ]:
oip_df.head()

,office_id,agcy_abr,site_fax_nbr,mail_st_abr,st_nm,office_name,agcy_ofc_type_cd,site_800_phone_nbr,mail_zip_cd,cnty_nm,...,latitude,last_chg_dt,office_800_phone_nbr,site_phn_nbr,mail_dlvy_adr,longitude,agcy_cd,site_phn_extn,mail_city_nm,st_abr
0,111617,FBC,,AL,Alabama,FBC - HOME OFFICE - BRINKLEY,9,NaN,36617,MOBILE,...,0.000000,2021-10-29 09:46:58.153,NaN,3185059349,806 BLACKMAN STREET ...,0.000000,99,NaN,MOBILE,AL
1,116570,FBC,,AL,Alabama,FBC â€“ REMOTE OFFICE â€“ GRADY ANDERSON,9,NaN,36832,LEE,...,NaN,2022-06-29 09:36:33.020,NaN,NaN,REMOTE OFFICE ...,NaN,99,NaN,AUBURN,AL
2,60081,NRCS,8557470601,AL,Alabama,ABBEVILLE SERVICE CENTER,4,NaN,36310-2748,HENRY,...,31.551256,2022-04-04 13:53:03.470,NaN,3345852284,810B COLUMBIA RD ...,-85.234787,16,NaN,ABBEVILLE,AL
3,104978,NRCS,2512758888,AL,Alabama,ALA-TOM RC&D,15,NaN,36451-0905,CLARKE,...,31.707643,2019-07-15 09:36:12.317,NaN,2512753184,PO BOX 905 ...,-87.776255,16,NaN,GROVE HILL,AL
4,108532,NRCS,2512758888,AL,Alabama,ALA-TOM RC&D COUNCIL,16,NaN,36451,CLARKE,...,31.707643,2019-07-15 09:36:12.317,NaN,2512753184,127A CLARK ST ...,-87.776255,16,NaN,GROVE HILL,AL

In [ ]:
oipsub_df = oip_df[['site_id', 'latitude', 'longitude']]

oipsub_df = oipsub_df.drop_duplicates()

oipsub_df['site_id'].sort_values()

oipsub_df.head()

   site_id   latitude  longitude
0    11072   0.000000   0.000000
1    16076        NaN        NaN
2     1981  31.551256 -85.234787
3     2744  31.707643 -87.776255
5     8910  34.499100 -86.966667

In [ ]:
merged1_df = distil1.merge(oipsub_df, left_on='Site ID', right_on='site_id')

merged1_df.to_excel("merged1.xlsx", index=False)

merged1_df.shape

(4640, 16)